/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIClases;

import Helpers.ImageUtils;
import Main.App;
import javax.swing.ImageIcon;
import javax.swing.JSlider;

/**
 *
 * @author author
 */
public class Home extends javax.swing.JFrame {
    
    private ImageUtils imageUtils = new ImageUtils();
    App app = App.getInstance();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        ImageIcon warsLogo = imageUtils.loadScaledImage("/GUI/Assets/Wars/logo.png", 140, 80);
        ImageIcon trekLogo = imageUtils.loadScaledImage("/GUI/Assets/Trek/logo.png", 120, 80);
        
        tvPanelUI1.getLogo().setIcon(warsLogo);
        tvPanelUI2.getLogo().setIcon(trekLogo);
        tvPanelUI1.getLogo().setText("");
        tvPanelUI2.getLogo().setText("");
        
        iaStatusLabel.setText("");
        winnerLabelID.setText("");

        // Se setean las imagenes que la lucha en la IA.
//        ImageIcon cartaPersonajeWars=  imageUtils.loadScaledImage(app.getIaArena().getPeleadorWars().getUrlSource(), 150, 200);
//        this.RegularShowCard.setIcon(cartaPersonajeWars);
//        ImageIcon cartaPersonajeTrek=  imageUtils.loadScaledImage(app.getIaArena().getPeleadorTrek().getUrlSource(), 150, 200);
//        this.AvatarCard.setIcon(cartaPersonajeTrek);
        // Se configura el slider 
        duracion.setOpaque(false);
        duracion.setMinimum(1);
        duracion.setMaximum(20);
        duracion.setValue(App.getDuracion());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tvPanelUI1 = new GUIClases.TvPanelUI();
        FightingTitle = new javax.swing.JLabel();
        tvPanelUI2 = new GUIClases.TvPanelUI();
        peleadorTrek = new GUIClases.FighterUI();
        peleadorWars = new GUIClases.FighterUI();
        Winner1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        roundLabel = new javax.swing.JLabel();
        iaStatusLabel = new javax.swing.JLabel();
        duracion = new javax.swing.JSlider();
        clockVelocity = new javax.swing.JLabel();
        winnerLabelID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 233, 223));
        jPanel1.setMinimumSize(new java.awt.Dimension(1130, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tvPanelUI1.setBackground(new java.awt.Color(255, 232, 31));
        jPanel1.add(tvPanelUI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        FightingTitle.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        FightingTitle.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle.setText("FIGHTING AREA");
        jPanel1.add(FightingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 10, 390, -1));
        jPanel1.add(tvPanelUI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));
        jPanel1.add(peleadorTrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, 460));
        jPanel1.add(peleadorWars, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, 460));

        Winner1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        Winner1.setForeground(new java.awt.Color(255, 255, 255));
        Winner1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Winner1.setText("Ganador:");
        jPanel1.add(Winner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 370, -1));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        roundLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        roundLabel.setForeground(new java.awt.Color(255, 255, 255));
        roundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundLabel.setText("Round: 0");

        iaStatusLabel.setBackground(new java.awt.Color(204, 0, 0));
        iaStatusLabel.setFont(new java.awt.Font("Montserrat", 1, 17)); // NOI18N
        iaStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        iaStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iaStatusLabel.setText("IA STATUS LABEL");
        iaStatusLabel.setToolTipText("");

        duracion.setForeground(new java.awt.Color(255, 255, 255));
        duracion.setMajorTickSpacing(9);
        duracion.setMaximum(20);
        duracion.setMinimum(1);
        duracion.setMinorTickSpacing(1);
        duracion.setPaintLabels(true);
        duracion.setPaintTicks(true);
        duracion.setToolTipText("Slider de Velocidad");
        duracion.setValue(10);
        duracion.setOpaque(true);
        duracion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                duracionStateChanged(evt);
            }
        });
        duracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duracionMouseClicked(evt);
            }
        });

        clockVelocity.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        clockVelocity.setForeground(new java.awt.Color(255, 255, 255));
        clockVelocity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockVelocity.setText("AJUSTE LA VELOCIDAD ");

        winnerLabelID.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        winnerLabelID.setForeground(new java.awt.Color(255, 255, 255));
        winnerLabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerLabelID.setText("Ganador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(iaStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(clockVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(roundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(winnerLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(clockVelocity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iaStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addComponent(winnerLabelID)
                .addGap(53, 53, 53))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 400, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void duracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duracionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionMouseClicked

    private void duracionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_duracionStateChanged
        // TODO add your handling code here:
        int newSpeed = getDuracion().getValue();
//        app.getIaArena().setCombatSpeed(newSpeed);
    }//GEN-LAST:event_duracionStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FightingTitle;
    private javax.swing.JLabel Winner1;
    private javax.swing.JLabel clockVelocity;
    private javax.swing.JSlider duracion;
    private javax.swing.JLabel iaStatusLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private GUIClases.FighterUI peleadorTrek;
    private GUIClases.FighterUI peleadorWars;
    private javax.swing.JLabel roundLabel;
    private GUIClases.TvPanelUI tvPanelUI1;
    private GUIClases.TvPanelUI tvPanelUI2;
    private javax.swing.JLabel winnerLabelID;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tvPanelUI1
     */
    public GUIClases.TvPanelUI getFranquiciaUI1() {
        return tvPanelUI1;
    }

    /**
     * @return the tvPanelUI2
     */
    public GUIClases.TvPanelUI getFranquiciaUI2() {
        return tvPanelUI2;
    }

    /**
     * @return the peleadorTrek
     */
    public GUIClases.FighterUI getPeleadorTrek() {
        return peleadorTrek;
    }

    /**
     * @return the peleadorWars
     */
    public GUIClases.FighterUI getPeleadorWars() {
        return peleadorWars;
    }

    /**
     * @return the iaStatusLabel
     */
    public javax.swing.JLabel getIaStatusLabel() {
        return iaStatusLabel;
    }

    /**
     * @return the WinnerLabelID
     */
    public javax.swing.JLabel getWinnerLabelID() {
        return winnerLabelID;
    }

    /**
     * @return the roundLabel
     */
    public javax.swing.JLabel getRoundLabel() {
        return roundLabel;
    }

    /**
     * @return the duracion
     */
    public javax.swing.JSlider getDuracion() {
        return duracion;
    }
}